export enum GAMESETTINGS {
  MINROUNDS = 1,
  MAXROUNDS = 50,
  MAXTIME = 600,
  MINTIME = 5,
}

export enum USERFIELDSCONSTS {
  MAX_NICKNAME_LENGTH = 17,
  MIN_NICKNAME_LENGTH = 10,
  MAX_PASSWORD_LENGTH = 50,
  MIN_PASSWORD_LENGTH = 10,
}
